---
- name: make a build dir
  file: state=directory name=/root/hdfs-journalnode-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/hdfs-journalnode-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/hdfs-journalnode-dockerized/start.sh mode=0755

- name: build a Docker image for HDFS journalnode
  command: docker build -t gitinsky/hdfs-journalnode:0.1.2 --rm /root/hdfs-journalnode-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/hdfs-journalnode:latest --rm /root/hdfs-journalnode-dockerized
